name: BuildRelease
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.1

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8.15.4
          run_install: false

      - name: Get pnpm store directory
        id: get-pnpm-store-directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.get-pnpm-store-directory.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Build
        run: pnpm build

      - name: Run Keycloakify
        run: npx keycloakify

  CreateGithubRelease:
    runs-on: ubuntu-latest
    needs: Test
    if: github.event_name == 'push'
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.1

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8.15.4
          run_install: false

      - name: Get pnpm store directory
        id: get-pnpm-store-directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.get-pnpm-store-directory.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Build
        run: pnpm build

      - name: Run Keycloakify
        run: npx keycloakify

      - name: Get Npm Version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - run: mv dist_keycloak/target/retrocompat-*.jar retrocompat-keycloak-theme.jar
      - run: mv dist_keycloak/target/*.jar keycloak-theme.jar
      - uses: softprops/action-gh-release@v1
        with:
          name: Release v${{ steps.package-version.outputs.current-version}}
          tag_name: v${{ steps.package-version.outputs.current-version}}
          target_commitish: ${{ github.head_ref || github.ref }}
          generate_release_notes: true
          draft: false
          files: |
            retrocompat-keycloak-theme.jar
            keycloak-theme.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

